### ISSUE TITLE
Upgrade Popper.js to v1

### ISSUE THREAD

**Issue by FezVrasta** [leroy-merlin-br/garden#182]
Hi, Popper.js v1 has been released few days ago, you may want to upgrade the version you are using.

**Comment by leandrogrillo** [comment]
hey @FezVrasta thanks for reporting :) we'll update it soon! and maybe use [greenkeeper](https://greenkeeper.io/) to maintain our dependencies updated :)

**Comment by fernandofleury** [comment]
so, are you guys doing this or not

**Comment by leandrogrillo** [comment]
yes @fernandofleury it's on track :)

**Comment by leandrogrillo** [comment]
Closed by [release v0.43.0](https://github.com/leroy-merlin-br/garden/releases/tag/v0.43.0)
