### ISSUE TITLE
Select fields are broken on Safari mobile

### ISSUE THREAD

**Issue by vitortalaia** [leroy-merlin-br/garden#195]
The select fields appearance on the mobile version of Safari is quite weird when there's a selected option:

![bs_realios_mobile_iphone 6s plus-9 0 1](https://cloud.githubusercontent.com/assets/5838414/23215947/f13840c6-f8f2-11e6-8d0c-51ed1ae4d1f5.jpg)

**Comment by fabricionaweb** [comment]
Solved in #198
