### ISSUE TITLE
Alterar nome dos menus

### ISSUE THREAD

**Issue by leandrogrillo** [leroy-merlin-br/garden#228]
Hoje temos alguns menus com nome prefixados, ex:

![image](https://cloud.githubusercontent.com/assets/1045308/24627317/c9636ea6-188a-11e7-9340-8a7cfd281028.png)

Precisamos trocar pra uma forma que não precise desse prefixo.

**Comment by fernandofleury** [comment]
e ai, vai ou nem

**Comment by leandrogrillo** [comment]
@fernandofleury pr aberto já https://github.com/leroy-merlin-br/garden/pull/229 :)
