### ISSUE TITLE
Remove jQuery from dev dependency

### ISSUE THREAD

**Issue by leandrogrillo** [leroy-merlin-br/garden#292]
and after we :rocket: v1 :)

Components:
- [x] Lazy Load
- [x] Scroll
- [x] Notification
- [x] Alert
- [x] Confirm
- [x] Modal
- [x] Collapse
- [x] Form
- [x] Tooltip
- [x] Validation

Obs: :no_entry_sign: blocked component due under discussion methods

**Comment by willamesoares** [comment]
Estou fazendo o `Confirm`

**Comment by leandrogrillo** [comment]
`Notification` :no_good_man:

**Comment by perna** [comment]
Parei o `Alert` por enquanto devido à dependência do component. `Modal`. Vou trabalhar no `LazyLoad`

**Comment by fabricionaweb** [comment]
Não havia muito oq fazer com o Scroll #298. Ele usa o JumpJS (que tbm nao usa jQuery)
Basicamente retirei a validacao do elemento e aproveitei pra mudar o `Object.assign`

**Comment by willamesoares** [comment]
For now, the Tooltip component is considered finished #299, but we have to bear in mind that the `$.data()` method must be refactored afterward.

**Comment by willamesoares** [comment]
I'm working on the `Collapse` component

**Comment by willamesoares** [comment]
Collapse done #302

**Comment by willamesoares** [comment]
Working on the `Validation` component.

**Comment by willamesoares** [comment]
`Validation` done #305

**Comment by fabricionaweb** [comment]
The `form` done in #306

**Comment by willamesoares** [comment]
Working on the `Modal` component.

**Comment by willamesoares** [comment]
`Modal` done #308

**Comment by willamesoares** [comment]
Now I'm back to `Confirm` :man_cartwheeling:

**Comment by fabricionaweb** [comment]
Working on `Notification`

**Comment by willamesoares** [comment]
`Confirm` done #310

**Comment by willamesoares** [comment]
Working on `Alert`

**Comment by willamesoares** [comment]
`Alert` done #315

**Comment by leandrogrillo** [comment]
We should add docblocks to some components/methods and utils

**Comment by leandrogrillo** [comment]
All components done :) maybe not all of them are working, but it's just a detail :B 

I'll close this issue and we'll keep working on others enhancements to :rocket: v1 :feelsgood:
