### ISSUE TITLE
Add doc blocks in components implementation

### ISSUE THREAD

**Issue by willamesoares** [leroy-merlin-br/garden#319]
Components:
- [x] Validation
- [x] Tooltip
- [x] Form
- [x] Collapse
- [x] Lazy Load
- [x] Modal
- [x] Confirm
- [x] Scroll
- [x] Notification
- [x] Alert

**Comment by willamesoares** [comment]
Working on `Notification`

**Comment by willamesoares** [comment]
`Notification` done.
https://github.com/leroy-merlin-br/garden/pull/317/commits/c7adc271f3e8e4fbb2d60481189163c78f86c12c

**Comment by willamesoares** [comment]
Working on `Alert`

**Comment by willamesoares** [comment]
`Alert` done #321

**Comment by willamesoares** [comment]
`Scroll` done #322

**Comment by willamesoares** [comment]
`Confirm` done #323

**Comment by willamesoares** [comment]
Working on `Modal`

**Comment by willamesoares** [comment]
`Modal` done #324

**Comment by willamesoares** [comment]
Working on `Collapse`

**Comment by leandrogrillo** [comment]
`Lazy Load` done #316

**Comment by leandrogrillo** [comment]
Working on `Collapse`

**Comment by willamesoares** [comment]
Working on `Form`

**Comment by leandrogrillo** [comment]
`Collapse` done #324

**Comment by willamesoares** [comment]
`Form` done #326

**Comment by willamesoares** [comment]
Working on `Tooltip`

**Comment by willamesoares** [comment]
`Tooltip` done #327

**Comment by willamesoares** [comment]
Working on `Validation`

**Comment by willamesoares** [comment]
`Validation` done #328
